name: Build and Check

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
            
env:
    CARGO_TERM_COLOR: always
                
jobs:
    build:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v3

        - name: Build token-extractor
          working-directory: ./token-extractor
          run: cargo build
        - name: Clippy token-extractor
          working-directory: ./token-extractor
          run: cargo clippy
        - name: Fmt token-extractor
          working-directory: ./token-extractor
          run: cargo fmt --check
 
        - name: Build main executable
          run: cargo build
        - name: Clippy main executable
          run: cargo clippy
        - name: Fmt main executable
          run: cargo fmt --check
  
        - name: Build clib
          working-directory: ./clib
          run: cargo build
        - name: Clippy clib
          working-directory: ./clib
          run: cargo clippy
        - name: Fmt clib
          working-directory: ./clib
          run: cargo fmt --check
